### ISSUE TITLE
Cannot install adapt-contrib-core with adapt-setup

### ISSUE THREAD

**Issue by swashbuck** [cgkineo/adapt-gulp-cli#21]
### Subject of the issue
Running `adapt-setup` and selecting `adapt-contrib-core` will add it to _adapt.json_. However, when then instructed to run `adapt install` to complete installation, it fails to install the core plugin.

```
adapt-contrib-core latest version [6.45.7]
<info> Installing plugins 22% completeTypeError: Cannot read properties of undefined (reading 'map')
    at Target.getType (file:///lib/node_modules/adapt-cli/lib/integration/Plugin.js:333:8)
    at async Target.getTypeFolder (file:///lib/node_modules/adapt-cli/lib/integration/Plugin.js:342:18)
    at async Target.install (file:///lib/node_modules/adapt-cli/lib/integration/Target.js:161:30)
```

Presumably this is because core does not have a _bower.json_ file which would allow it to be installed from the Bower repository. When using `adapt create course`, it appears that the core plugin is git cloned and switched to the appropriate branch. Also, the core plugin is not added to `adapt.json` when using the Adapt CLI, unlike with `adapt-setup`.

Should `adapt-setup` install the core plugin the same way as [Adapt CLI](https://github.com/adaptlearning/adapt-cli)? If so, should `adapt-contrib-core` be removed from the list of plugins that are selectable when running `adapt-setup`?

### Your environment
* adapt-setup 1.1.0

**Comment by oliverfoster** [comment]
adapt-cli doesn't install adapt-contrib-core as it's not a proper plugin, the core is installed by a [preinstall script](https://github.com/adaptlearning/adapt_framework/blob/11d5f1e9d10473df9a7b90dcfe5a079cab7c202d/package.json#L10) in adapt_framework on `npm install`. Please do not consider core as an installable plugin. Plugins are components, extensions, menus and themes, core was always part of adapt_framework, I separated it because they're distinctly different bits of software architecturally and in v6 core will be installable and will become a plugin the same as all others.

**Comment by swashbuck** [comment]
Ok, would it be worthwhile to omit `adapt-contrib-core` from the list until V6 is released?

https://github.com/cgkineo/adapt-setup/blob/9231b3fa710bf108241997a0362bba79268b659f/lib/Setup.js#L85

```
async getPluginChoices(answers, input) {
	const getPluginsByUser = user => {
		const list = this.plugins.filter(({ url, name }) => {
			return url.split("/")[3] === user &&
				name.toLowerCase().includes(input.toLowerCase()) &&
				!name.toLowerCase().includes('adapt-contrib-core');
		});
```

Or, alternatively, list it like `adapt-contrib-core - Framework v6+ only`

**Comment by oliverfoster** [comment]
I don't mind either. Exclusion is probably easier from a user's perspective.
